version: '3'

tasks:
  #
  # Lint
  #
  lint:
    cmds:
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.50.1 golangci-lint run -v

  lint:fix:
    cmds:
      - golangci-lint run --fix

  #
  # Test
  #
  test:
    cmds:
      - go test ./internal/...

  #
  # Build
  #
  build:
    cmds:
      - go build -o bin/users_service_crqs ./cmd

  #
  # Docker
  #
  docker:build:
    cmds:
      - docker build -t users_service_cqrs .

  docker:run:
    cmds:
      - docker run users_service_cqrs --env-file=./.env

  #
  # gRPC
  #
  grpc:generate:
    cmds:
      - |
        protoc --proto_path=./api/proto \
          --go_opt=paths=source_relative --go_out=./internal/ports/grpc \
          --go-grpc_opt=paths=source_relative --go-grpc_out=./internal/ports/grpc \
          ./api/proto/*.proto

  #
  # OpenAPI
  #
  oapi:generate:
    cmds:
      - | 
        oapi-codegen \
          -package http \
          -generate server,types,spec \
          ./api/openapi/users_service.yaml > ./internal/ports/http/server.gen.go
      - task oapi:generate:client

  oapi:generate:client:
    cmds:
      - |
        oapi-codegen \
          -package client \
          -generate client,types,spec \
          ./api/openapi/users_service.yaml > ./tests/client/client.gen.go