version: '3'

tasks:
  lint:
    cmds:
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.50.1 golangci-lint run -v

  lint:fix:
    cmds:
      - golangci-lint run --fix

  test:
    cmds:
      - go test ./internal/...

  build:
    cmds:
      - go build -o bin/users_service_crqs ./cmd

  #
  # Docker
  #
  docker:build:
    cmds:
      - docker build -t users_service_cqrs .

  docker:run:
    cmds:
      - docker run users_service_cqrs --env-file=./.env

  #
  # gRPC
  #

  #
  # OpenAPI
  #
  oapi:generate:
    cmds:
      - | 
        oapi-codegen \
          -package http \
          -generate server,types,spec \
          ./api/openapi/users_service.yaml > ./internal/ports/http/server.gen.go