version: '3'

tasks:
  lint:
    cmds:
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.50.1 golangci-lint run -v

  build:
    cmds:
      - go build -o bin/users_service_crqs ./cmd
