// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for GetUsersByStatusParamsStatus.
const (
	Blocked   GetUsersByStatusParamsStatus = "blocked"
	Unblocked GetUsersByStatusParamsStatus = "unblocked"
)

// GenericResponse defines model for GenericResponse.
type GenericResponse struct {
	Message *string `json:"message,omitempty"`
}

// User defines model for User.
type User struct {
	Email     *openapi_types.Email `json:"email,omitempty"`
	FirstName *string              `json:"firstName,omitempty"`
	Id        *openapi_types.UUID  `json:"id,omitempty"`
	LastName  *string              `json:"lastName,omitempty"`

	// Status User Status
	Status *string `json:"status,omitempty"`
}

// UserList defines model for UserList.
type UserList = []User

// GetUsersByStatusParams defines parameters for GetUsersByStatus.
type GetUsersByStatusParams struct {
	// Status User status "blocked" / "unblocked"
	Status GetUsersByStatusParamsStatus `form:"status" json:"status"`
}

// GetUsersByStatusParamsStatus defines parameters for GetUsersByStatus.
type GetUsersByStatusParamsStatus string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Finds users by status
	// (GET /users)
	GetUsersByStatus(w http.ResponseWriter, r *http.Request, params GetUsersByStatusParams)
	// Finds Pets by status
	// (POST /users/{id}/block)
	BlockUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update an existing pet
	// (POST /users/{id}/unblock)
	UnblockUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetUsersByStatus operation middleware
func (siw *ServerInterfaceWrapper) GetUsersByStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersByStatusParams

	// ------------- Required query parameter "status" -------------

	if paramValue := r.URL.Query().Get("status"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersByStatus(w, r, params)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// BlockUser operation middleware
func (siw *ServerInterfaceWrapper) BlockUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BlockUser(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UnblockUser operation middleware
func (siw *ServerInterfaceWrapper) UnblockUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnblockUser(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.GetUsersByStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/{id}/block", wrapper.BlockUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/{id}/unblock", wrapper.UnblockUser)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RVS3PbNhD+Kxi0R4qQIilpeUoTuxl14jS16l5iHyBwScIhHgaWsjUe/fcOQFKWLObh",
	"dsa5aChy8e3iewD3VBhljQaNnmb31IsKFI+P70CDk+IcvDXaQ3hlnbHgUEIsUOA9L+MH3FigGfXopC7p",
	"dpv0b8zqGgTSbUIvPLhjDFBc1vHhjitbhyXXptKv4/tUGEUTWhinONKsK04ed0toIZ3HD1zBIRJWELsO",
	"rJD5YemrVy+LKcz5aDUXYjQDmI34+JfJiE8nc3gJMz7/dbI/StPIfAi35kOD/GEqPVTtkWMTecjBCyct",
	"SqNpFrkiy/Zjsoezqo34DAONv0T4e+kxwEsEFfv87KCgGf2JPcjOOs1Z5OoBiTvHN3QbsOEOwWlenxgx",
	"MG2FaH3GWCmxalZBNFbU5lZ8Zo0H50ce3FoKGIkb50elYeenv52cnaYq7KNx9dMRooC6MGEUYTRygXte",
	"Cm5QUptUVFyXXMvX5c5M2+TR7G//Ol+SHJQhMnCsQCMPn4gpCCddX4KGKK55CSTOk9KE1lJAlwod9aZn",
	"i7//64bY+8Xb0w/LyEkQAJzyfxbLtqiDyxjzt7wswaXSsFjCghEkRmsE8Xy/IqFrcL7d4Tgdp5OAaixo",
	"biXN6DQdp1OaUMuxinq2U4WnEvBY4LOmRmlrIMhLTwTXZAXEOrOWOeTkVmJFhFEq8GW54wg5aY3pU3Lh",
	"47JJEn5fxN8pKYwjCB6lLgOX4UCIrC9ymtF3gHEzbza7BARUBRhn/DQYljZJ5LKPyCUljFzSRu/+xyDZ",
	"2uRAM3QNBAvRjN404DY06UX0fUsHN410kPfFbUiizXSjaPZpL4y7LvTq+9J6FfDbYzWy/mI87r0MOgrA",
	"ra2liKSwax/2eb83wnfHOeZ/MNKHHPpGCPC+aGqyEyOsm7WDHRYv9JrXMg9SkjWvG4jnj2+U4m5DM/q7",
	"1Llvk0JWG7KjNLgnENea7Sosao3H7mW+ZZGueEMcqh1lClZ9UCmevV9W6BundKDfGv81o3d2irt7muOP",
	"7PwmbKu7hv6X6F/T+vFd/XSJn2uM3jz7DA/65yPgk+zThTAaaFDcC5tzBMI1gTsZzx5iAUOLRX6k2kWL",
	"1un2HI78kd5YDnhj+c38L06Ib8JYkLe1s+Paj4BEGySFaXRXNT+u+ifgtfcu3AloXx+aYli9IVuEZeDW",
	"vVgPF3LGWG0EryvjMZuOx2O6vdr+GwAA//92M/l6AQsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
