name: ci
on:
  push

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://postgres:password@postgres:5432/users_service_cqrs_db?sslmode=disable
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-task@v1
        with:
          version: 3.10.0
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.19'

      - name: Build
        run: task build

      - name: Boot app
        run: docker-compose up -d

      - name: Unit Test
        run: task test

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest