name: ci
on:
  push

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://postgres:password@postgres:5432/users_service_cqrs_db?sslmode=disable
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14.6
        # Provide the password for postgres
        env:
          POSTGRES_DB: users_service_cqrs_db
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-task@v1
        with:
          version: 3.10.0
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.19'

      - name: Build
        run: task build

      - name: Setup tests
        run: |
          task mig:up
          task seeds:up

      - name: Unit Test
        run: task test

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest